title: Gerardo Moreno Urriola
logo: /assets/img/profile_photo.png
description: Research student of the Robotics, Intelligent Systems and Simulation group, UTP. Studies focused on robotics, simulation, virtual environments and motion capture together with computer vision.
Currently working as Data Engineer & BI Consultant at COPA Airlines.
show_downloads: false
theme: jekyll-theme-minimal
