title: Gerardo Moreno Urriola
logo: /assets/img/profile_photo.png
description: Research student of the Robotics, Intelligent Systems and Simulation group, UTP.
show_downloads: false
theme: jekyll-theme-minimal
